#!/bin/sh
############################################################
# <bsn.cl fy=2013 v=onl>
# 
#        Copyright 2013, 2014 Big Switch Networks, Inc.       
# 
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#        http://www.eclipse.org/legal/epl-v10.html
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
# 
# </bsn.cl>
############################################################
#
# Platform: Quanta LY6
#
############################################################

echo $$ > /var/run/frontled.pid

wait=3

frontled=$(dirname $0)/frontled

while true
do
    psu1_status=$(sensors *-i2c-*-58 | sed "s/(.*)//" | grep "Vin.*0\.00 V")
    psu2_status=$(sensors *-i2c-*-59 | sed "s/(.*)//" | grep "Vin.*0\.00 V")
    fan_status=$(sensors *-i2c-*-4e | grep " 0 RPM")
    if [ "$psu1_status" = "" ]; then
        $frontled psu1 green
    else
        $frontled psu1 red
    fi

    if [ "$psu2_status" = "" ]; then
        $frontled psu2 green
    else
        $frontled psu2 red
    fi

    if [ "$fan_status" = "" ]; then
        $frontled fan green
    else
        $frontled fan red
    fi

    sleep $wait
done

exit 0

