#!/bin/sh
############################################################
# <bsn.cl fy=2013 v=onl>
# 
#        Copyright 2013, 2014 Big Switch Networks, Inc.       
# 
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#        http://www.eclipse.org/legal/epl-v10.html
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
# 
# </bsn.cl>
############################################################
#
# Platform: Quanta LY2R
#
############################################################

cur_dir=$(dirname $0)
if [ -x $cur_dir/functions ]; then
	. $cur_dir/functions
else
	echo "$cur_dir/functions not found"
	exit 1
fi

# pca9698 pin define:
# 0: power mode (0: high, 1: low)
# 1: interrupt (0: active, 1: inactive)
# 2: present (0: present, 1: not present)
# 3: module reset (0: enable, 1: disable)
pca9698_21=$(gpio_find 21)

for port in $(seq 0 3); do
	offset=$(eval echo "\$pca953x_p${port}2")
	gpio=$(($pca9698_21 + $offset))

	present=$(gpio_get $gpio)
	if [ $present -eq 0 ]; then
		echo "port $(($port+49)): present"
	else
		echo "port $(($port+49)): not present"
	fi
done
