#!/bin/sh
############################################################
# <bsn.cl fy=2013 v=onl>
# 
#        Copyright 2013, 2014 Big Switch Networks, Inc.       
# 
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#        http://www.eclipse.org/legal/epl-v10.html
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
# 
# </bsn.cl>
############################################################
#
# Platform: Quanta LY2R
#
############################################################

cur_dir=$(dirname $0)
if [ -x $cur_dir/functions ]; then
	. $cur_dir/functions
else
	echo "$cur_dir/functions not found"
	exit 1
fi

# Enable SFP module power
# pca9555_24p10 ~ pca9555_24p13, pca9555_25p10 ~ pca9555_25p13
#   are sfp power, 8 ports per pin
# pca9555_25p14 is qsfp power
pca9555_24=$(gpio_find 24)
pca9555_24p10=$(($pca9555_24 + $pca953x_p10))
pca9555_24p13=$(($pca9555_24 + $pca953x_p13))
pca9555_25=$(gpio_find 25)
pca9555_25p10=$(($pca9555_25 + $pca953x_p10))
pca9555_25p14=$(($pca9555_25 + $pca953x_p14))

for i in `seq $pca9555_24p10 $pca9555_24p13`; do
	gpio_set $i 0
done

for i in `seq $pca9555_25p10 $pca9555_25p14`; do
	gpio_set $i 0
done
