############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=all
PACKAGE_NAMES=platform-config-x86_64-accton_wedge_16x-r0
include ../../../../../make/debuild.mk
